# Site settings
title: Texas Tribune Style Guides
# email:
description: "These are the style guides for the Texas Tribune."
baseurl: "/styleguides"
# url: "http://yourdomain.com"
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
kramdown:
  # use github flavored markdown for consistency with github
  input: GFM
  # parse markdown inside block level html tags
  parse_block_html: true
permalink: pretty
exclude: ['Makefile', 'Gemfile', 'Gemfile.lock', 'Gruntfile.js', 'package.json', 'node_modules/']
